name: Linux Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update repositories
        run: sudo apt update

      - name: Install dependencies
        run: |
          sudo apt-get -y install libusb-1.0-0-dev maven wget unzip
          cd /opt
          wget --no-check-certificate https://download.processing.org/processing-3.5.4-linux64.tgz
          tar -xf processing-3.5.4-linux64.tgz
          
      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          cd "${{runner.workspace}}"
          sudo git clone https://github.com/pavels/rtl-sdr
          cd rtl-sdr
          sudo cmake .
          sudo make
          cd ..
          sudo mkdir -p $HOME/sketchbook/libraries/rtlspektrum/library
          cd "$HOME/sketchbook/libraries"
          sudo wget https://github.com/sojamo/controlp5/releases/download/v2.2.5/controlP5-2.2.5.zip
          sudo unzip -x controlP5-2.2.5.zip
          sudo wget https://github.com/Viproz/controlp5/releases/download/v2.2.7b/controlP5.jar
          sudo cp -f controlP5.jar controlP5/library
          cd "${{runner.workspace}}"
          sudo git clone https://github.com/alphafox02/processing-rtlspektrum-lib.git
          cd processing-rtlspektrum-lib
          sudo mvn package
          sudo cp library.properties "$HOME/sketchbook/libraries/rtlspektrum/"
          sudo cp target/rtlspektrum.jar "$HOME/sketchbook/libraries/rtlspektrum/library/"
          sudo cp target/lib/bridj-0.7.0.jar "$HOME/sketchbook/libraries/rtlspektrum/library/bridj.jar"
          cd ..
          sudo rm -r spektrum
          git clone https://github.com/alphafox02/spektrum.git
          sudo /opt/processing-3.5.4/processing-java --sketch="${{runner.workspace}}/spektrum/" --output="${{runner.workspace}}/spektrum_out" --force --export
          sudo mkdir -p spektrum_out/data
          sudo cp -L rtl-sdr/src/librtlpower.so spektrum_out/lib/
          sudo cp -L rtl-sdr/src/librtlsdr.so spektrum_out/lib/
          sudo tar -czf spektrum-linux64.tar.gz spektrum_out

      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
          name: Spektrum-Latest
          path: ${{runner.workspace}}/*.tar.gz
