name: Linux Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update repositories
        run: sudo apt update

      - name: Install dependencies
        run: |
          sudo apt-get -y install libusb-1.0-0-dev maven wget unzip
          cd /opt
          wget --no-check-certificate https://download.processing.org/processing-3.5.4-linux64.tgz
          tar -xf processing-3.5.4-linux64.tgz
          cd /usr/src

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          git clone https://github.com/pavels/rtl-sdr
          cd rtl-sdr
          cmake .
          make
          cd ..
          mkdir -p /usr/src/sketchbook/libraries/rtlspektrum/library
          cd /usr/src/sketchbook/libraries"
          wget https://github.com/sojamo/controlp5/releases/download/v2.2.5/controlP5-2.2.5.zip
          unzip -x controlP5-2.2.5.zip
          wget https://github.com/Viproz/controlp5/releases/download/v2.2.7b/controlP5.jar
          cp -f controlP5.jar controlP5/library
          cd /usr/src
          git clone https://github.com/pavels/processing-rtlspektum-lib
          cd processing-rtlspektum-lib
          mvn package
          cp library.properties /usr/src/sketchbook/libraries/rtlspektrum/
          cp target/rtlspektrum.jar /usr/src/sketchbook/libraries/rtlspektrum/library/
          cp target/lib/bridj-0.7.0.jar /usr/src/sketchbook/libraries/rtlspektrum/library/bridj.jar
          cd ..
          /opt/processing-3.5.4/processing-java --sketch="/usr/src" --output="/usr/spektrum" --force --export
          mkdir -p spektrum/data
          cp -L rtl-sdr/src/librtlpower.so spektrum/lib/
          cp -L rtl-sdr/src/librtlsdr.so spektrum/lib/
          tar -czf spektrum-linux64.tar.gz spektrum

      - name: Upload ZIP
        uses: actions/upload-artifact@v2
        with:
          name: Spektrum-Latest
          path: ${{runner.workspace}}/build/*.tar.gz
